---
DOMAIN_NAME: craft
LOCAL_IP: 10.10.10.10
################################################################################

# Ansible

################################################################################
################################################################################
ansible_roles_list:
- bgrrtt.zim
- geerlingguy.firewall
- geerlingguy.nginx
- geerlingguy.php
- geerlingguy.mysql
- geerlingguy.php-mysql
################################################################################

# Vagrant

################################################################################
################################################################################

# `vagrant_box` can also be set to bento/ubuntu-14.04 or bento/ubuntu-16.04
vagrant_box: bento/ubuntu-14.04
vagrant_user: vagrant

# If you need to run multiple instances of Craft VM, set a unique hostname,
# and IP address for each instance.
vagrant_hostname: craft
vagrant_tld: dev
vagrant_ip: 192.168.88.88

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

################################################################################

# Craft VM

################################################################################
################################################################################

# Minimum required versions.
craftvm_vagrant_version_min: '1.9'
craftvm_ansible_version_min: '2.2'

# Project Info
craftvm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
craftvm_project_code: craft
craftvm_webserver: nginx
craftvm_db_backend: mysql

################################################################################

# Craft CMS

################################################################################
################################################################################

# Required Craft settings.
craft_env: local
craft_site_url: "//{{ ansible_fqdn }}"
craft_base_url: "//{{ ansible_fqdn }}"
craft_base_path: "/"
craft_app_path: ""
craft_app_owner: "{{ craftvm_user }}"
craft_db_host: localhost
craft_db_user: "{{ vagrant_user }}"
craft_db_password: "{{ vagrant_user }}"
craft_db_name: "{{ vagrant_hostname }}"

# Settings for installing a Craft.
craft_major_version: 2
craft_domain: "{{ vagrant_hostname }}.{{ vagrant_tld }}"
craft_site_name: "Drupal"


################################################################################

# Webserver

################################################################################
################################################################################

nginx_remove_default_vhost: true
nginx_ppa_use: true

nginx_vhosts:
  - server_name: "adminer.{{ vagrant_hostname }}.{{ vagrant_tld }}"
    root: "{{ adminer_install_dir }}"
    is_php: true
  - listen: "80"
    server_name: "{{ ansible_fqdn }}"
    root: /site/public
    index: "index.php index.html index.htm"
    extra_parameters: |
      # configuration from nginx-partials
      # include /etc/nginx/nginx-partials/*.conf;
      # root
      location / {
        try_files $uri $uri/ /index.php$is_args$args;
      }
      # craft
      location ^~ /admin {
        try_files $uri $uri/ /index.php$is_args$args;
      }
      location ^~ /cpresources {
          try_files $uri $uri/ /index.php$is_args$args;
      }
      # php
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_intercept_errors on;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param SCRIPT_NAME $fastcgi_script_name;
          fastcgi_param CRAFTVM_ENVIRONMENT "{{ craft_env }}";
          fastcgi_param CRAFTVM_DB_HOST "{{ craft_db_host }}";
          fastcgi_param CRAFTVM_DB_NAME "{{ craft_db_name }}";
          fastcgi_param CRAFTVM_DB_USER "{{ craft_db_user }}";
          fastcgi_param CRAFTVM_DB_PASS "{{ craft_db_password }}";
          fastcgi_param CRAFTVM_SITE_URL "{{ craft_site_url }}";
          fastcgi_param CRAFTVM_BASE_URL "{{ craft_base_url }}";
          fastcgi_param CRAFTVM_BASE_PATH "{{ craft_base_path }}";
          include fastcgi_params;
      }
      # no .htaccess
      location ~ /\.ht {
          deny all;
      }

################################################################################

# Database

################################################################################
################################################################################
# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300

# MySQL databases and users.
mysql_databases:
  - name: "{{ craft_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ craft_db_user }}"
    host: "%"
    password: "{{ craft_db_password }}"
    priv: "{{ craft_db_name }}.*:ALL"
################################################################################

# Firewall

################################################################################
################################################################################
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true
################################################################################

# php

################################################################################
################################################################################
# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# Must rebuild to change versions.
php_version: "7.1"
php_install_recommends: yes
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
# php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

php_conf_paths:
  - "/etc/php/{{ php_version }}/fpm"
  - "/etc/php/{{ php_version }}/nginx"
  - "/etc/php/{{ php_version }}/cli"
php_extension_conf_paths:
  - "/etc/php/{{ php_version }}/fpm/conf.d"
  - "/etc/php/{{ php_version }}/nginx/conf.d"
  - "/etc/php/{{ php_version }}/cli/conf.d"
php_fpm_daemon: "php{{ php_version }}-fpm"
php_fpm_conf_path: "/etc/php/{{ php_version }}/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"
php_mysql_package: "php{{ php_version }}-mysql"
php_date_timezone: "America/Detroit"

php_webserver_daemon: nginx

php_fpm_pool_user: vagrant
php_fpm_pool_group: vagrant

php_packages:
  - "php{{ php_version }}"
  - "php-apcu"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-cgi"
  - "php{{ php_version }}-common"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-dev"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-gd"
  - php-imagick
  - "php{{ php_version }}-imap"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-mcrypt"
  - "php{{ php_version }}-odbc"
  - "php{{ php_version }}-opcache"
  - php-pear
  - "php{{ php_version }}-sqlite3"
  - "php{{ php_version }}-tidy"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-xmlrpc"
  - "php{{ php_version }}-zip"
  - libpcre3-dev
  # - "php{{ php_version }}-yaml"
  # - php7.0-mysqlnd




################################################################################

# Composer

################################################################################
################################################################################
# composer_path: /usr/bin/composer
# composer_home_path: "/home/{{ drupalvm_user }}/.composer"
# composer_home_owner: "{{ drupalvm_user }}"
# composer_home_group: "{{ drupalvm_user }}"
# composer_global_packages:
#   - { name: hirak/prestissimo, release: '^0.3' }
#
################################################################################

# Scripts

################################################################################
################################################################################
# # Run specified scripts before or after VM is provisioned. Path is relative to
# # the `provisioning/playbook.yml` file.
# pre_provision_scripts: []
# post_provision_scripts: []
#   # - "../examples/scripts/configure-solr.sh"
#
################################################################################

# Nodejs

################################################################################
################################################################################
# # Node.js configuration (if enabled above).
# # Valid examples: "0.10", "0.12", "4.x", "5.x".
# nodejs_version: "0.12"
# nodejs_npm_global_packages: []
# nodejs_install_npm_user: "{{ drupalvm_user }}"
# npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
################################################################################

# Ruby

################################################################################
################################################################################
# # Ruby Configuration (if enabled above).
# ruby_install_gems_user: "{{ drupalvm_user }}"
# ruby_install_gems: []
################################################################################

# Utilities

################################################################################
################################################################################
# # Comment out any extra utilities you don't want to install. If you don't want
# # to install *any* extras, set this value to an empty set, e.g. `[]`.
# installed_extras:
#   - adminer
#   # - blackfire
#   - drupalconsole
#   - drush
#   # - elasticsearch
#   # - java
#   - mailhog
#   # - memcached
#   # - newrelic
#   # - nodejs
#   - pimpmylog
#   # - redis
#   # - ruby
#   # - selenium
#   # - solr
#   # - tideways
#   # - upload-progress
#   - varnish
#   # - xdebug
#   # - xhprof
#
# Add any extra apt or yum packages you would like installed.
# extra_packages:
#   - sqlite
#
################################################################################

# Extras

################################################################################
################################################################################
# # Varnish Configuration (if enabled above).
# varnish_listen_port: "81"
# varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
# varnish_default_backend_host: "127.0.0.1"
# varnish_default_backend_port: "80"
#
# # Pimp my Log settings.
# pimpmylog_install_dir: /usr/share/php/pimpmylog
# pimpmylog_grant_all_privs: true
#
# # XDebug configuration. XDebug is disabled by default for better performance.
# php_xdebug_default_enable: 0
# php_xdebug_coverage_enable: 0
# php_xdebug_cli_enable: 1
# php_xdebug_remote_enable: 1
# php_xdebug_remote_connect_back: 1
# # Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
# php_xdebug_idekey: PHPSTORM
# php_xdebug_max_nesting_level: 256
#
# # Solr Configuration (if enabled above).
# solr_version: "5.5.3"
# solr_xms: "64M"
# solr_xmx: "128M"
#
# # Selenium configuration.
# selenium_version: 2.53.0
#
# # Other configuration.
# dashboard_install_dir: /var/www/dashboard
# known_hosts_path: ~/.ssh/known_hosts
# ssh_home: "{{ drupal_core_path }}"
