---
# Craft VM
################################################################################
craftvm_name: Craft
craftvm_hostname: craft
craftvm_ip: 10.10.10.10
craftvm_url: "{{ ansible_fqdn }}"
craftvm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
craftvm_webserver: nginx

# Vagrant
################################################################################
vagrant_box: bento/ubuntu-14.04
vagrant_memory: 2048
vagrant_cpus: 2
