---
# tasks file for zim
- name: install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - zsh
    - git

- name: install prezto
  git: repo=https://github.com/bgrrtt/dotfiles.git dest=~/.zim
  become: false

- name: get rid of existing ~/.zshrc
  file: path=~/.zshrc state=absent
  become: false

- name: .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
  become: false

- name: .zlogin
  template:
    src: zlogin.j2
    dest: ~/.zlogin
  become: false

- name: .zimrc
  template:
    src: zimrc.j2
    dest: ~/.zimrc
  become: false

- name: switch to Zsh
  user: name={{ user }} shell=/usr/bin/zsh
  become: true
